apps:
  archive_unpacker: unz
  archive_viewer: unz -v
  audio_editor: audacity &
  audio_player: play
  doc_editor: soffice &
  file_manager: xdesktop &
  image_editor: gimp &
  image_viewer: gqview &
  pdf_annotator: xournal &
  pdf_viewer: evince &
  text_editor: xedit &
  video_editor: shotcut &
  video_player: play
  web_browser: firefox
mimeapps:
  application/gzip:                 archive_unpacker  archive_viewer
  application/java-archive:         archive_unpacker  archive_viewer
  application/json:                 text_editor
  application/msword:               doc_editor
  application/pdf:                  pdf_annotator     pdf_viewer
  application/pgp-encrypted:        archive_unpacker  archive_viewer
  application/vnd.debian:           archive_unpacker  archive_viewer
  application/vnd.ms-excel:         doc_editor
  application/vnd.oasis:            doc_editor
  application/vnd.openxmlformats-officedocument:      doc_editor
  application/vnd.rar:              archive_unpacker  archive_viewer
  application/vnd.sqlite3:          archive_unpacker  archive_viewer
  application/vnd.wordperfect:      doc_editor
  application/x-7z-compressed:      archive_unpacker  archive_viewer
  application/x-ace:                archive_unpacker  archive_viewer
  application/x-apple-diskimage:    archive_unpacker  archive_viewer
  application/x-bzip2:              archive_unpacker  archive_viewer
  application/xhtml+xml:            text_editor       web_browser
  application/x-iso9660-appimage:   archive_unpacker  archive_viewer
  application/x-lzma:               archive_unpacker  archive_viewer
  application/x-rpm:                archive_unpacker  archive_viewer
  application/x-tar:                archive_unpacker  archive_viewer
  application/x-xojpp:              pdf_annotator
  application/x-xz:                 archive_unpacker  archive_viewer
  application/yaml:                 text_editor
  application/zip:                  archive_unpacker  archive_viewer
  application/zstd:                 archive_unpacker  archive_viewer
  image/:                           image_editor      image_viewer
  video/:                           video_player
  text/:                            text_editor
  text/csv:                         doc_editor
  text/html:                        text_editor       web_browser
parameters:
  web_agent: Mozilla/5.0 (X11; Linux x86_64; rv:153.0) Gecko/20100101 Firefox/153.0
  web_homepage: http://drtuxwang.fast-page.org/bookmarks.xhtml
  web_mail: https://mail.google.com
