#!/usr/bin/env bash
#
# Docker container init script
#

run_vnc() {
    echo "Starting SSHD server..."
    sudo /usr/sbin/sshd -D &
    sleep 1
    ps -ef | grep "[0-9] /usr/sbin/sshd -D"

    echo "Starting VNC server..."
    sudo -u owner vncserver \
        -geometry 1024x768 \
        -depth 24 \
        -localhost \
        -SecurityTypes None > /dev/null 2>&1
    vncserver -list | grep ^:
}

if [ "$XAUTH" ]
then
    touch $HOME/.Xauthority
    xauth add $(uname -n)/${XAUTH#*/}
fi

if [ "$SSH_PUBKEY" ]
then
    echo "$SSH_PUBKEY" > $HOME/.ssh/authorized_keys
    echo "$SSH_PUBKEY" > /home/owner/.ssh/authorized_keys
fi

if [ $# = 0 ]
then
    exec bash -l
elif [ "$1" = "-svnc" ]
then
    run_vnc
    sleep infinity
else
    exec "$@"
fi
