FROM ubuntu:18.10

# Install base packages
RUN apt-get update && \
	apt-get install --no-install-recommends -y \
		dh-python \
		iputils-ping \
		net-tools \
		openssh-client \
		pciutils \
		python3 \
		python3-pip \
		vim && \
	apt-get clean && \
	python3 -m pip install --upgrade pip
