FROM centos:6

# Install base packages
RUN yum -y install epel-release && \
	yum -y update && \
	yum -y install net-tools openssh-clients pciutils python34 vim xz && \
	curl https://bootstrap.pypa.io/get-pip.py | python3.4 && \
	python3 -m pip install --upgrade pip && \
	rm -rf \
		/root/.cache \
		/root/.bash_logout \
		/root/.bash_profile \
		/root/.cshrc \
		/root/.pki \
		/root/.tcshrc \
		/root/anaconda-ks.cfg \
		/root/install.log \
		/root/install.log.syslog && \
	echo -e '#!/bin/sh\n/usr/bin/tty | sed -e "s/^\/24$/\/dev\/console/"' > /usr/local/bin/tty && \
	chmod ugo+rx /usr/local/bin/tty
