FROM drtuxwang/ubuntu:16.04

# Install extra packages
RUN apt-get install --no-install-recommends -y \
		csh \
		ksh \
		python3-dev \
		python3-pip \
		python3-setuptools \
		tcsh \
		tmux \
		wget && \
	python3 -m pip install pep8 pylint && \
	apt-get clean
