#!/bin/bash
#
# Docker container init script
#

run_vnc() {
    echo "Starting SSHD server..."
    sudo /usr/sbin/sshd -D &
    sleep 1
    ps -ef | grep "[0-9] /usr/sbin/sshd -D"

    echo "Starting VNC server..."
    sudo -u owner vncserver -SecurityTypes None > /dev/null 2>&1
    vncserver -list | grep ^:
}


mkdir -p "$HOME"
for FILE in /home/home*.tar
do
    tar xf $FILE -C $HOME
    rm -f $FILE
done

if [ "$XAUTH" ]
then
    touch $HOME/.Xauthority
    xauth add $(uname -n)/${XAUTH#*/}
fi

echo "$SSH_PUBKEY" > $HOME/.ssh/authorized_keys
echo "$SSH_PUBKEY" > /home/owner/.ssh/authorized_keys

if [ $# = 0 ]
then
    exec bash -l
elif [ "$1" = "-vnc" ]
then
    run_vnc
    sleep infinity
else
    exec "$@"
fi

