#!/usr/bin/env bash
#
# 0AD 0.27.1 (Debian 13) portable app
# - Requires: bwrap (Bubblewrap)
#

set -e


app_settings() {
    NAME="0ad"
    VERSION="0.27.1"
    PORT="linux64-x86-glibc_2.41"

    APP_DIRECTORY="${NAME}_$VERSION-$PORT"
    APP_FILES="
        https://deb.debian.org/debian/pool/main/0/0ad/0ad_0.27.0-2+b1_amd64.deb
        https://deb.debian.org/debian/pool/main/0/0ad-data/0ad-data_0.27.0-1_all.deb
        https://deb.debian.org/debian/pool/main/0/0ad-data/0ad-data-common_0.27.0-1_all.deb

        https://deb.debian.org/debian/pool/main/b/boost1.83/libboost-filesystem1.83.0_1.83.0-4.2_amd64.deb
        https://deb.debian.org/debian/pool/main/e/enet/libenet7_1.3.18+ds-1+b1_amd64.deb
        https://deb.debian.org/debian/pool/main/f/fmtlib/libfmt10_10.1.1+ds1-4_amd64.deb
        https://deb.debian.org/debian/pool/main/f/fonts-freefont/fonts-freefont-ttf_20211204+svn4273-2_all.deb
        https://deb.debian.org/debian/pool/main/g/gloox/libgloox18_1.0.28-1+b3_amd64.deb
        https://deb.debian.org/debian/pool/main/m/miniupnpc/libminiupnpc18_2.2.8-2+b2_amd64.deb
        https://deb.debian.org/debian/pool/main/p/pcre2/libpcre2-32-0_10.46-1~deb13u1_amd64.deb
        https://deb.debian.org/debian/pool/main/t/tex-gyre/fonts-texgyre_20180621-6_all.deb
        https://deb.debian.org/debian/pool/main/w/wxwidgets3.2/libwxbase3.2-1t64_3.2.8+dfsg-2_amd64.deb
        https://deb.debian.org/debian/pool/main/w/wxwidgets3.2/libwxgtk-gl3.2-1t64_3.2.8+dfsg-2_amd64.deb
        https://deb.debian.org/debian/pool/main/w/wxwidgets3.2/libwxgtk3.2-1t64_3.2.8+dfsg-2_amd64.deb
    "
    APP_REMOVE="
        etc/
        usr/share/applications/
        usr/share/doc/
        usr/share/icons/
        usr/share/man/
        usr/share/lintian/
        usr/share/metainfo/
        usr/share/texmf/
    "
    APP_START="usr/games/pyrogenesis"
    APP_LINK="0ad"
}

app_start() {
    MYDIR=$(realpath "${0%/*}")
    [ "${_SANDBOX_PARENT:-}" ] && exec "$MYDIR/$APP_START" "$@"
    exec /usr/bin/bwrap \
        --ro-bind / / \
        --tmpfs /home \
        --tmpfs /tmp \
        --dev dev \
        --dev-bind-try /dev/dri /dev/dri \
        --bind-try /run/user/$(id -u)/pulse /run/user/$(id -u)/pulse \
        --bind-try "$HOME/.config/0ad" "$HOME/.config/0ad" \
        --overlay-src /usr --overlay-src "$MYDIR/usr" --ro-overlay /usr \
        -- "$MYDIR/$APP_START" "$@"
}


source "${0%/*}/create-portable-app.bash"
