#!/usr/bin/env bash
#
# LibreOffice 25.2.7.2 (Offical) portable app
#

set -e


app_settings() {
    NAME="libreoffice"
    VERSION="25.2.7.2"
    PORT="linux64-x86"

    APP_DIRECTORY="${NAME}_$VERSION-$PORT"
    APP_FILES="
        https://downloadarchive.documentfoundation.org/libreoffice/old/$VERSION/deb/x86_64/LibreOffice_${VERSION}_Linux_x86-64_deb.tar.gz
    "
    APP_UNPACK="
        LibreOffice_*_deb/DEBS/*.deb
    "
    APP_REMOVE="
        LibreOffice_*_deb/
        opt/libreoffice${VERSION%.*.*}/share/extensions/nlpsolver/
        opt/libreoffice${VERSION%.*.*}/share/extensions/wiki-publisher/
        usr/
    "
    APP_SHELL="
        mv opt/libreoffice*/* .
        rm -r opt/
    "
    APP_START="program/soffice"
}

app_start() {
    MYDIR=$(realpath "${0%/*}")
    exec "$MYDIR/$APP_START" "$@"
}


source "${0%/*}/create-portable-app.bash"
