#!/usr/bin/env bash
#
# Wesnoth 1.18.3 (Debian 13) portable app
# - Requires: bwrap (Bubblewrap)
#

set -e


app_settings() {
    NAME="wesnoth"
    VERSION="1.18.5"
    PORT="linux64-x86-glibc_2.41"

    APP_DIRECTORY="${NAME}_$VERSION-$PORT"
    APP_FILES="
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18_1.18.5-1_amd64.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-data_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-did_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-dm_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-dw_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-ei_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-httt_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-l_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-low_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-music_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-nr_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-server_1.18.5-1_amd64.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-sof_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-sota_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-sotbe_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-thot_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-tools_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-trow_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-tsg_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-ttb_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-utbs_1.18.5-1_all.deb
        https://deb.debian.org/debian/pool/main/w/wesnoth-1.18/wesnoth-1.18-wof_1.18.5-1_all.deb

        https://deb.debian.org/debian/pool/main/b/boost1.83/libboost-filesystem1.83.0_1.83.0-4.2_amd64.deb
        https://deb.debian.org/debian/pool/main/b/boost1.83/libboost-iostreams1.83.0_1.83.0-4.2_amd64.deb
        https://deb.debian.org/debian/pool/main/b/boost1.83/libboost-locale1.83.0_1.83.0-4.2_amd64.deb
        https://deb.debian.org/debian/pool/main/b/boost1.83/libboost-program-options1.83.0_1.83.0-4.2_amd64.deb
        https://deb.debian.org/debian/pool/main/b/boost1.83/libboost-random1.83.0_1.83.0-4.2_amd64.deb
        https://deb.debian.org/debian/pool/main/b/boost1.83/libboost-thread1.83.0_1.83.0-4.2_amd64.deb
        https://deb.debian.org/debian/pool/main/f/fonts-adf/fonts-adf-oldania_0.20190904-3_all.deb
        https://deb.debian.org/debian/pool/main/f/fonts-android/fonts-droid-fallback_8.1.0r7-1~1.gbp36536b_all.deb
        https://deb.debian.org/debian/pool/main/f/fonts-lato/fonts-lato_2.015-1_all.deb
        https://deb.debian.org/debian/pool/main/f/fonts-lohit-beng-bengali/fonts-lohit-beng-bengali_2.91.5-3_all.deb
    "
    APP_REMOVE="
        etc/
        usr/share/applications/
        usr/share/bug/
        usr/share/doc/
        usr/share/doc-base/
        usr/share/games/wesnoth/${VERSION%.*}/images/misc/l10n/
        usr/share/games/wesnoth/${VERSION%.*}/locale/
        usr/share/icons/
        usr/share/lintian/
        usr/share/man/
        usr/share/metainfo/
    "
    APP_START="usr/games/wesnoth-${VERSION%.*}"
    APP_LINK="wesnoth"
}

app_start() {
    MYDIR=$(realpath "${0%/*}")
    [ "${_SANDBOX_PARENT:-}" ] && exec "$MYDIR/$APP_START" "$@"
    exec /usr/bin/bwrap \
        --ro-bind / / \
        --tmpfs /home \
        --tmpfs /tmp \
        --dev dev \
        --ro-bind-try "$MYDIR" "$MYDIR" \
        --dev-bind-try /dev/dri /dev/dri \
        --dev-bind-try /dev/shm /dev/shm \
        --bind-try /run/user/$(id -u)/pulse /run/user/$(id -u)/pulse \
        --bind-try "$HOME/.config/wesnoth" "$HOME/.config" \
        --overlay-src /usr --overlay-src "$MYDIR/usr" --ro-overlay /usr \
        -- "$MYDIR/$APP_START" "$@"
}


source "${0%/*}/create-portable-app.bash"
