FROM drtuxwang/debian:latest

RUN apt-get install --no-install-recommends -y \
		csh \
		ksh \
		python3-dev \
		python3-setuptools \
		sudo \
		tcsh \
		tmux \
		x11-utils \
		x11-xserver-utils \
		xfce4-terminal \
		xfonts-base \
		wget && \
	python3 -m pip install pycodestyle pep8==1.7.0 pylint && \
	apt-get clean

# Xfce setup
COPY tmpdir/config/terminalrc /home/docker/.config/xfce4/terminal/terminalrc
ENV XDG_CURRENT_DESKTOP=XFCE

# Bash shell setup
COPY tmpdir/bin/ /opt/software/bin/
COPY tmpdir/config/docker-init tmpdir/config/docker-init-home /etc/
COPY tmpdir/config/login /home/docker/.login
COPY tmpdir/config/profile /home/docker/.profile
COPY tmpdir/config/tmux.conf /home/docker/.tmux.conf
COPY tmpdir/config/vimrc /home/docker/.vimrc
ENTRYPOINT ["/etc/docker-init"]
