FROM debian:9

# Install base packages
RUN apt-get update && \
	apt-get install --no-install-recommends -y \
		net-tools \
		openssh-client \
		pciutils \
		python3 \
		python3-pip \
		vim && \
	apt-get clean
