FROM debian-base

# Install extra packages
RUN apt-get install --no-install-recommends -y csh ksh tcsh && \
    apt-get install --no-install-recommends -y file sudo tmux wget && \
    apt-get install --no-install-recommends -y python3 python3-dev python3-pip && \
    python3 -m pip install pep8 pylint

# Install X-windows packages
RUN apt-get install --no-install-recommends -y x11-xserver-utils x11-utils xfonts-base && \
    apt-get install --no-install-recommends -y xfce4-terminal libgtk-3-0 libasound2

# Add scripts
COPY tmpdir/bin/ /opt/software/bin/
COPY tmpdir/config/docker-init /etc/
COPY tmpdir/config/docker-init-home /etc/

# Docker account
COPY tmpdir/config/login /home/docker/.login
COPY tmpdir/config/profile /home/docker/.profile
COPY tmpdir/config/terminalrc /home/docker/.config/xfce4/terminal/terminalrc
COPY tmpdir/config/tmux.conf /home/docker/.tmux.conf
COPY tmpdir/config/vimrc /home/docker/.vimrc

# Configure start
ENV XDG_CURRENT_DESKTOP=XFCE
CMD /etc/docker-init
