FROM debian-shell:latest

# Install packages for building Python
RUN apt-get install -y libbz2-dev libdb5.3-dev libreadline6-dev libsqlite3-dev libssl-dev zlib1g-dev

# Install packages for building TMUX
RUN apt-get install -y libevent-dev libncurses5-dev

# Install packages for building OpenMPI
RUN apt-get install -y gfortran
