#!/bin/bash -u
#
# Fix group and others file/directory read access recursively
#

for FILE in $(find $*)
do
    if [ -x "$FILE" ]
    then
        chmod 755 $FILE
    else
        chmod 644 $FILE
    fi
done
