#!/usr/bin/env bash

case `uname` in
Darwin)
    export CPPFLAGS="-I/usr/local/opt/libxml2/include $CPPFLAGS"
    export LDFLAGS="-L/usr/local/opt/libxml2/lib $LDFALGS"
    export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

umask 022
./configure
make

ls -l src/aria2c
strip src/aria2c
ls -l src/aria2c
