#!/bin/bash
#
# Docker container init script
#

mkdir -p "$HOME"
for FILE in /home/home*.tar
do
    tar xf $FILE -C $HOME
    rm -f $FILE
done

if [ "$XAUTH" ]
then
    touch $HOME/.Xauthority
    xauth add $(uname -n)/${XAUTH#*/}
fi

if [ "$SSH_PUBKEY" ]
then
    echo "Starting SSHD server..."
    echo "$SSH_PUBKEY" > $HOME/.ssh/authorized_keys
    sudo /usr/sbin/sshd -D &
    sleep 1
    ps -ef | grep "[0-9] /usr/sbin/sshd -D"
fi
if [ "$SVNCSERVER" ]
then
    echo "Starting VNC server..."
    vncserver -SecurityTypes None > /dev/null 2>&1
    vncserver -list | grep ^:
fi

if [ $# = 0 ]
then
    exec bash -l
fi
exec "$@"
