#!/bin/sh

IMAGE=debian-geeqie
CPUSHARE="--cpu-shares=100000 --cpu-quota=1000000"
MEMLIMIT="-memory-reservation=64m --memory=1024m"
PASSWD="$HOME/.docker-passwd"

if [ ! -f "$PASSWD" ]
then
    echo -e "root:x:0:0:root:/root:/bin/bash\n$USER:x:$(id -u):$(id -g):-:$HOME:/bin/bash" > $PASSWD
fi

mkdir -p $HOME/.config/geeqie 2> /dev/null
DIR=$PWD
docker run --cpu-period=100000 $CPUSHARE $MEMLIMIT \
    --rm \
    --volume="$PASSWD:/etc/passwd:ro" \
    --volume="/etc/group:/etc/group:ro" \
    --volume=/tmp/.X11-unix:/tmp/.X11-unix \
    --volume=$HOME/.config/geeqie:$HOME/.config/geeqie \
    --volume="$DIR:$DIR" \
    --workdir "$DIR"  \
    --env USER=$USER \
    --env TERM=$TERM \
    --env DISPLAY=$DISPLAY \
    --name $IMAGE \
    --hostname $IMAGE \
    --network none \
    $IMAGE /etc/docker-init /opt/software/bin/gqview "$DIR"
