FROM drtuxwang/debian-base:testing

# Install extra packages
RUN apt-get install --no-install-recommends -y \
		csh \
		file \
		python3 \
		python3-dev \
		python3-pip \
		python3-setuptools \
		sudo \
		tcsh \
		tmux \
		wget && \
	apt-get install --no-install-recommends -y ksh ||: && \
	python3 -m pip install pep8 pylint && \
	apt-get clean

# Add scripts
COPY tmpdir/bin/ /opt/software/bin/
COPY tmpdir/config/docker-init /etc/
COPY tmpdir/config/docker-init-home /etc/

# Docker account
COPY tmpdir/config/login /home/docker/.login
COPY tmpdir/config/profile /home/docker/.profile
COPY tmpdir/config/tmux.conf /home/docker/.tmux.conf
COPY tmpdir/config/vimrc /home/docker/.vimrc

# Configure start
ENTRYPOINT ["/etc/docker-init"]
