#!/bin/bash
#
# Start X for Docker container
#

if [ "$(id -u)" != 0 ]; then
    exec sudo $0 "$@"
fi

# Change docker user ID
if [ "$1" ]; then
    sed -i "s/docker:x:1000:/docker:x:$1:/" /etc/passwd
    chown -R $1:100 /home/docker
fi

# Run using docker user account
sudo -u docker bash -l
