#!/bin/bash
#
# Docker container init script
#

echo -e "Running \"$0\"..."

if [ ! "$ID" ]; then
    exec /bin/bash -l
fi

# Processi "id" output
ID=$(echo "$ID" | sed -e "s/[=()]/ /g")
ARRAY=(${ID//:/ })
USER_ID=${ARRAY[1]}
USER_NAME=${ARRAY[2]}
GROUP_ID=${ARRAY[4]}
GROUP_NAME=${ARRAY[5]}

# Create user account
echo "$GROUP_NAME:x:$GROUP_ID:" >> /etc/group
echo "$USER_NAME:x:$USER_ID:$GROUP_ID:Docker User:/home/$USER_NAME:/bin/bash" >> /etc/passwd
cat << EOF > /etc/sudoers.d/docker
Defaults:$USER_NAME !requiretty
$USER_NAME ALL=(ALL) NOPASSWD: ALL
Defaults umask = 0022
EOF

# Create "/home/docker" directory
if [ ! -d "/home/docker" ]; then
    mkdir /home/$USER_NAME
else
    mv /home/docker /home/$USER_NAME
fi
chown -R $USER_ID:$GROUP_ID /home/$USER_NAME

# Switch to user
su - $USER_NAME -c "export DISPLAY=$DISPLAY; exec bash -l"
