#!/bin/bash
#
# Docker container OpenVPN init script
#

echo -e "Running \"$0\"..."

# Fix "/etc/resolv.conf"
cp -p /etc/resolv.conf /etc/resolv.conf-orig
umount /etc/resolv.conf
mv /etc/resolv.conf-orig /etc/resolv.conf
apt-get install -y resolvconf

# Call default init
exec /etc/docker-init
