#!/bin/bash
#
# Docker container init script
#

echo -e "\nRunning \"$0\"..."

# Process plugins
for FILE in /etc/docker-init-*
do
    $FILE
done

# Switch to user $USER
if [ "$USER" ]
then
    export HOME=$(grep "^$USER:" /etc/passwd | cut -f6 -d:)
    cd $HOME
    echo -e "\nStarting \"$USER\" login shell..."
    sudo -E -u $USER bash -l
else
    echo -e "\nStarting \"root\" login shell..."
    /bin/bash -l
fi

echo -e "\nFinished \"$0\"..."
if [ "$$" = 1 ]
then
    echo "Stopping Docker container!"
fi
