#!/bin/bash
#
# Docker container X init script
#

xauth add $(uname -n)/${XAUTH#*/} 2> /dev/null
if [ "$(id -u)" != 0 ]
then
    ln -s /root /home/$(id -un)
fi

if [ $# = 0 ]
then
    exec bash -l
fi
exec "$@"
