#!/bin/bash
#
# Fix "/etc/resolv.conf" readonly problem in Docker for OpenVPN
#

echo "Running \"$0\"..."

# Umount "/etc/resolv.conf" and restore static copy
cp -p /etc/resolv.conf /etc/resolv.conf-orig
umount /etc/resolv.conf
mv /etc/resolv.conf-orig /etc/resolv.conf

# Re-install OpenVPN
apt-get install -y resolvconf
