#!/bin/bash
#
# Add user: -env ID=$(id)
#

echo -e "Running \"$0\"..."

if [ ! "$ID" ]; then
    exit 1
fi

# Process "id" output
ID=$(echo "$ID" | sed -e "s/[=()]/ /g")
ARRAY=(${ID//:/ })
USER_ID=${ARRAY[1]}
USER_NAME=${ARRAY[2]}
GROUP_ID=${ARRAY[4]}
GROUP_NAME=${ARRAY[5]}

# Create user account
echo "$GROUP_NAME:x:$GROUP_ID:" >> /etc/group
echo "$USER_NAME:x:$USER_ID:$GROUP_ID:Docker User:/home/$USER_NAME:/bin/bash" >> /etc/passwd
cat << EOF > /etc/sudoers.d/docker
Defaults:$USER_NAME !requiretty
$USER_NAME ALL=(ALL) NOPASSWD: ALL
Defaults umask = 0022
EOF

# Create user home directory
HOME=/home/$USER_NAME
if [ -d "/home/docker" ]; then
    for FILE in $(cd /home/docker; find -type f); do
        if [ ! -f "$HOME/$FILE" ]; then
            mkdir -p "$HOME/${FILE%/*}" 2> /dev/null
            cp -p "/home/docker/$FILE" "$HOME/$FILE"
        fi
    done
fi
chown -R $USER_ID:$GROUP_ID $HOME
