#!/bin/bash
#
# Docker container init script
#

echo -e "\nRunning \"$0\"..."

# Process plugins
for FILE in /etc/docker-init-*; do
    $FILE
done

# Switch to user: -env ID=$(id)
if [ "$ID" ]; then
    ID=$(echo "$ID" | sed -e "s/[=()]/ /g")
    ARRAY=(${ID//:/ })
    USER_NAME=${ARRAY[2]}
    export HOME=/home/$USER_NAME
    cd $HOME
    sudo -E -u $USER_NAME bash -l
else
    /bin/bash -l
fi

echo -e "\n\"$0\" finished!"
