#!/bin/bash
#
# Docker container X init script
#

xauth add $(uname -n)/${XAUTH#*/} 2> /dev/null

if [ "$SANDBOX_USER" ]
then
    SANDBOX_HOME=$(grep "^$SANDBOX_USER:" /etc/passwd | cut -f6 -d:)
    mkdir -p "$SANDBOX_HOME"
    cp -p /root/.profile /root/.tmux.conf /root/.vimrc "$SANDBOX_HOME"
    chown -R $(grep "^$SANDBOX_USER:" /etc/passwd | cut -f3-4 -d:) "$SANDBOX_HOME"

    if [ ! "$SANDBOX_ROOT" ]
    then
        if [ $# = 0 ]
        then
            HOME=$(grep "^$SANDBOX_USER:" /etc/passwd | cut -f6 -d:) exec su -p - $SANDBOX_USER
        else
            echo "$@" | HOME=$(grep "^$SANDBOX_USER:" /etc/passwd | cut -f6 -d:) su -p - $SANDBOX_USER -c bash
            exit $?
        fi
    fi
fi

if [ $# = 0 ]
then
    exec bash -l
fi
exec "$@"
