[main]
plugins=ifupdown,keyfile
dns=none

[ifupdown]
managed=false

[device]
wifi.scan-rand-mac-address=no

[global-dns]
options=timeout:1,attempts:1

[connection]
ipv4.dns-priority=100
ipv6.dns-priority=90
ipv6.ip6-privacy=2
ipv6.method=auto
