#!/bin/sh
#
# Run command in offline mode
#
# Copy to "/usr/local/bin/offline" and add to "/etc/sudoers":
# ALL ALL = NOPASSWD:/usr/local/bin/offline
#

if [ $# = 0 ]
then
    echo "Usage: offline command"
    exit 1
fi

MYUNAME=`/usr/bin/id | sed -e 's/^[^(]*(\([^)]*\)).*$/\1/'`

if [ "$MYUNAME" = root ]
then
    unshare -n "$@"
else
    sudo $0 -n sudo -u $MYUNAME "$@"
fi
