" General settings
set background=dark
set encoding=utf-8
set scrolloff=3
set title
let &titlestring=hostname().':%F  %y%r%m %a'

" Mouse support
set mouse=a
set ttymouse=xterm

" Spell Checking - Use "]=", "[=", "z=", "zg" & "zw"
set spell spelllang=en_gb
highlight SpellBad cterm=underline ctermbg=0
highlight SpellCap cterm=underline ctermbg=0
highlight SpellLocal cterm=underline ctermbg=0
highlight SpellRare cterm=underline ctermbg=0

" Status line
set ruler
set showcmd

" Syntax highlighting
syntax on
set hlsearch
set list listchars=tab:▸\ ,trail:·
set showmatch
set tabstop=4
highlight OverLength ctermbg=0 guibg=lightgrey
match OverLength /\%101v.\+/
highlight TabChar ctermbg=0 guibg=lightgrey
2match TabChar /\t/
highlight TrailingSpace ctermbg=0 guibg=lightgrey
match TrailingSpace /\s\+$/

" Turn off annoying features
set lazyredraw
set nobackup
set noerrorbells
set noswapfile
set novisualbell

" Workaround cursor bugs (ie Tmux)
map <Esc>[A <Up>
map <Esc>[B <Down>
map <Esc>[C <Right>
map <Esc>[D <Left>
cmap <Esc>[A <Up>
cmap <Esc>[B <Down>
cmap <Esc>[C <Right>
cmap <Esc>[D <Left>
imap <Esc>[A <Up>
imap <Esc>[B <Down>
imap <Esc>[C <Right>
imap <Esc>[D <Left>

" Python settings
autocmd Filetype python call SetPython()
function SetPython()
    match OverLength /\%80v.\+/
endfunction
