FROM drtuxwang/debian-base:8

# Install extra packages
RUN apt-get install --no-install-recommends -y \
		libasound2 \
		libgtk-3-0 \
		x11-xserver-utils \
		x11-utils \
		xfce4-terminal \
		xfonts-base && \
	apt-get clean
