FROM drtuxwang/debian-shell

# Install extra packages
RUN apt-get install --no-install-recommends -y \
		libasound2 \
		libgtk-3-0 \
		x11-xserver-utils \
		x11-utils \
		xfce4-terminal \
		xfonts-base && \
	apt-get clean

# Docker account
COPY tmpdir/config/terminalrc /home/docker/.config/xfce4/terminal/terminalrc

# Configure start
ENV XDG_CURRENT_DESKTOP=XFCE
