FROM drtuxwang/debian-base

# Install extra packages
RUN apt-get install --no-install-recommends -y \
		csh \
		file \
		ksh \
		python3 \
		python3-dev \
		python3-pip \
		tcsh \
		sudo \
		tmux \
		wget && \
	python3 -m pip install pep8 pylint

# Install X-windows packages
RUN apt-get install --no-install-recommends -y \
	libasound2 \
	libgtk-3-0 \
	x11-xserver-utils \
	x11-utils \
	xfce4-terminal \
	xfonts-base

# Add scripts
COPY tmpdir/bin/ /opt/software/bin/
COPY tmpdir/config/docker-init /etc/
COPY tmpdir/config/docker-init-home /etc/

# Docker account
COPY tmpdir/config/login /home/docker/.login
COPY tmpdir/config/profile /home/docker/.profile
COPY tmpdir/config/terminalrc /home/docker/.config/xfce4/terminal/terminalrc
COPY tmpdir/config/tmux.conf /home/docker/.tmux.conf
COPY tmpdir/config/vimrc /home/docker/.vimrc

# Configure start
ENV XDG_CURRENT_DESKTOP=XFCE
ENTRYPOINT ["/etc/docker-init"]
