#!/bin/sh

IMAGE=debian-geeqie
CPUSHARE="--cpu-shares=100000 --cpu-quota=1000000"
MEMLIMIT="-memory-reservation=64m --memory=1024m"

mkdir -p $HOME/.config/geeqie 2> /dev/null
DIR=$PWD
docker run --cpu-period=100000 $CPUSHARE $MEMLIMIT \
    --rm \
    --interactive \
    --tty \
    --volume="/etc/passwd:/etc/passwd:ro" \
    --volume="/etc/group:/etc/group:ro" \
    --volume=/tmp/.X11-unix:/tmp/.X11-unix \
    --volume=$HOME/.config/geeqie:$HOME/.config/geeqie \
    --volume="$DIR:$DIR" \
    --workdir "$DIR"  \
    --env USER=$USER \
    --env TERM=$TERM \
    --env DISPLAY=$DISPLAY \
    --name $IMAGE \
    --hostname $IMAGE \
    $IMAGE /etc/docker-init /opt/software/bin/gqview
