FROM drtuxwang/centos

# Install sandbox environment packages
RUN yum -y install mesa-libGL SDL tmux wget xorg-x11-server-utils xorg-x11-xauth && \
	yum clean all && \
	rm -rf /root/.??* && \
	echo "sandbox:x:99999:99999::/home/sandbox:/bin/bash" >> /etc/passwd && \
	echo "sandbox:x:99999" >> /etc/group && \
	chmod -R 777 /home && \
	wget https://github.com/krallin/tini/releases/download/v0.18.0/tini-amd64 -O /tini && \
	chmod 755 /tini
