- name: Copy file to "{{ home_directory }}/.Xresources"
  copy:
    src: '{{ config_directory }}/Xresources'
    dest: '{{ home_directory }}/.Xresources'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0600'
  tags:
  - user-home

- name: Ensure "{{ home_directory }}/.config" directory exists
  file:
    path: '{{ home_directory }}/.config'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - autostart

- name: Copy file to "{{ home_directory }}/.config/autorun-start.bash"
  copy:
    src: '{{ config_directory }}/autorun-start.bash'
    dest: '{{ home_directory }}/.config/'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - autostart

- name: Check "{{ home_directory }}/.config/autorun-start-opt.bash" file status
  stat:
    path: '{{ home_directory }}/.config/autorun-start-opt.bash'
  register: autorun_start_opt
  tags:
  - user-home
  - autostart

- name: Copy file to "{{ home_directory }}/.config/autorun-start-opt.bash"
  when: not autorun_start_opt.stat.exists
  copy:
    src: '{{ config_directory }}/autorun-start-opt.bash'
    dest: '{{ home_directory }}/.config/'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - autostart

- name: Copy file to "{{ home_directory }}/.config/autostart/autorun.desktop"
  copy:
    src: '{{ config_directory }}/autorun.desktop'
    dest: '{{ home_directory }}/.config/autostart/'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - autostart

- name: Ensure "{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml" directory exists
  file:
    path: '{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml'
    state: directory
    recurse: true
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - thunar

- name: Copy files to "{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml/"
  loop:
  - xfce4-keyboard-shortcuts.xml
  - xfce4-terminal.xml
  - thunar.xml
  copy:
    src: '{{ config_directory }}/{{ item }}'
    dest: '{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml/{{ item | regex_replace("-deb.*$", "") }}'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - terminal
  - thunar

- name: Copy file to "{{ home_directory }}/.config/mimeapps.list"
  copy:
    src: '{{ config_directory }}/mimeapps.list'
    dest: '{{ home_directory }}/.config/'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - mimeapps

- name: Ensure "{{ home_directory }}/.local/share/applications" directory exists
  file:
    path: '{{ home_directory }}/.local/share/applications'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - mimeapps

- name: Copy files to "{{ home_directory }}/.local/share/applications" directory
  with_fileglob:
  - '{{ config_directory }}/userapp-*.desktop'
  copy:
    src: '{{ item }}'
    dest: '{{ home_directory }}/.local/share/applications/'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - mimeapps

- name: Ensure "{{ home_directory }}/.config/geeqie/applications" directory exists
  file:
    path: '{{ home_directory }}/.config/geeqie/applications'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - geeqie

- name: Copy files to "{{ home_directory }}/.config/geeqie/" directory
  loop:
  - accels
  - geeqierc.xml
  copy:
    src: '{{ config_directory }}/{{ item }}'
    dest: '{{ home_directory }}/.config/geeqie/{{ item | regex_replace("-deb.*$", "") }}'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - geeqie

- name: Copy files to "{{ home_directory }}/.config/geeqie/applications/" directory
  loop:
  - geeqie-animate.desktop
  - geeqie-edit.desktop
  - geeqie-play.desktop
  - geeqie-rotate90.desktop
  - geeqie-rotate270.desktop
  copy:
    src: '{{ config_directory }}/{{ item }}'
    dest: '{{ home_directory }}/.config/geeqie/applications/{{ item }}'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - geeqie

- name: Ensure "{{ home_directory }}/.config/vlc" directory exists
  file:
    path: '{{ home_directory }}/.config/vlc'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - vlc

- name: Copy file to "{{ home_directory }}/.config/vlc/vlcrc"
  copy:
    src: '{{ config_directory }}/vlcrc'
    dest: '{{ home_directory }}/.config/vlc'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - vlc

- name: Template file to "{{ home_directory }}/.config/autorun-boot.bash"
  when: user == "owner"
  template:
    src: autorun-boot.bash
    dest: '{{ home_directory }}/.config/autorun-boot.bash'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - bootrun

- name: Cron entry for starting "{{ home_directory }}/.config/autorun-boot.bash"
  when: user == "owner"
  cron:
    name: Start "{{ home_directory }}/.config/autorun-boot.bash"
    user: '{{ user }}'
    special_time: reboot
    job: 'sleep 20 && SHELL=/bin/bash {{ home_directory }}/.config/autorun-boot.bash'
  tags:
  - user-home
  - bootrun
