- name: Copy file to "{{ home_directory }}/.Xresources"
  copy:
    src: '{{ config_directory }}/Xresources'
    dest: '{{ home_directory }}/.Xresources'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0600'
  tags:
  - user-home

- name: Ensure "{{ home_directory }}/.config" directory exists
  file:
    path: '{{ home_directory }}/.config'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - autostart

- name: Copy file to "{{ home_directory }}/.config/autostart.bash"
  copy:
    src: '{{ config_directory }}/autostart.bash'
    dest: '{{ home_directory }}/.config/'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - autostart

- name: Check "{{ home_directory }}/.config/autostart-opt.bash" file status
  stat:
    path: '{{ home_directory }}/.config/autostart-opt.bash'
  register: autostart_opt_bash
  tags:
  - user-home
  - autostart

- name: Copy file to "{{ home_directory }}/.config/autostart-opt.bash"
  when: not autostart_opt_bash.stat.exists
  copy:
    src: '{{ config_directory }}/autostart-opt.bash'
    dest: '{{ home_directory }}/.config/'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - autostart

- name: Copy file to "{{ home_directory }}/.config/autostart/autostart.desktop"
  copy:
    src: '{{ config_directory }}/autostart.desktop'
    dest: '{{ home_directory }}/.config/autostart/'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - autostart

- name: Ensure "{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml" directory exists
  file:
    path: '{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml'
    state: directory
    recurse: true
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - thunar

- name: Copy files to "{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml/"
  loop:
  - xfce4-keyboard-shortcuts.xml-deb12
  - thunar.xml-deb12
  copy:
    src: '{{ item }}'
    dest: '{{ home_directory }}/.config/xfce4/xfconf/xfce-perchannel-xml/{{ item | regex_replace("-deb.*$", "") }}'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - thunar

- name: Copy file to "{{ home_directory }}/.config/mimeapps.list"
  copy:
    src: '{{ config_directory }}/mimeapps.list'
    dest: '{{ home_directory }}/.config/'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - mimeapps

- name: Ensure "{{ home_directory }}/.local/share/applications" directory exists
  file:
    path: '{{ home_directory }}/.local/share/applications'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - mimeapps

- name: Copy files to "{{ home_directory }}/.local/share/applications" directory
  with_fileglob:
  - "{{ config_directory }}/userapp-*.desktop"
  copy:
    src: '{{ item }}'
    dest: '{{ home_directory }}/.local/share/applications/'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - mimeapps

- name: Ensure "{{ home_directory }}/.config/geeqie/applications" directory exists
  file:
    path: '{{ home_directory }}/.config/geeqie/applications'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - geeqie

- name: Copy files to "{{ home_directory }}/.config/geeqie/" directory
  loop:
  - accels-deb12
  - geeqierc.xml-deb12
  copy:
    src: '{{ item }}'
    dest: '{{ home_directory }}/.config/geeqie/{{ item | regex_replace("-deb.*$", "") }}'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - geeqie

- name: Copy files to "{{ home_directory }}/.config/geeqie/applications/" directory
  loop:
  - animate.desktop
  - gimp.desktop
  - play.desktop
  - rotate-90.desktop
  - rotate-270.desktop
  copy:
    src: '{{ item }}'
    dest: '{{ home_directory }}/.config/geeqie/applications/{{ item }}'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - geeqie

- name: Ensure "{{ home_directory }}/.config/vlc" directory exists
  file:
    path: '{{ home_directory }}/.config/vlc'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - vlc

- name: Copy file to "{{ home_directory }}/.config/vlc/vlcrc"
  copy:
    src: vlcrc
    dest: '{{ home_directory }}/.config/vlc'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - vlc

- name: Ensure "{{ home_directory }}/.config/xfce4/terminal" directory exists
  file:
    path: '{{ home_directory }}/.config/xfce4/terminal'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - terminal

- name: Copy file to "{{ home_directory }}/.config/xfce4/terminal/terminalrc"
  copy:
    src: '{{ config_directory }}/terminalrc'
    dest: '{{ home_directory }}/.config/xfce4/terminal'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - terminal

- name: Template file to "{{ home_directory }}/.config/bootstart.bash"
  when: user == "owner"
  template:
    src: bootstart.bash
    dest: '{{ home_directory }}/.config/bootstart.bash'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - bootstart

- name: Cron entry for starting "{{ home_directory }}/.config/bootstart.bash"
  when: user == "owner"
  cron:
    name: Start "{{ home_directory }}/.config/bootstart.bash"
    user: '{{ user }}'
    special_time: reboot
    job: 'sleep 20 && SHELL=/bin/bash {{ home_directory }}/.config/bootstart.bash'
  tags:
  - user-home
  - bootstart
