- name: Include "home-setup.yaml" tasks
  include_tasks: home-setup.yaml
  tags:
  - user-home

- name: Include "user-setup.yaml" tasks
  when: user not in ["root", ansible_user]
  include_tasks: user-setup.yaml
  tags:
  - user-home
  - netnice
  - ssh

- name: Include "cmdline-apps.yaml" tasks
  when: cmdline_apps
  include_tasks: cmdline-apps.yaml
  tags:
  - user-home
  - htop
  - tmux

- name: Include "gui-apps-deb12.yaml" tasks
  when:
  - user not in ["root", ansible_user] and gui_apps
  - ansible_distribution == 'Debian' and ansible_distribution_major_version | int < 13
  include_tasks: gui-apps-deb12.yaml
  tags:
  - user-home
  - autostart
  - bootrun
  - mimeapps
  - geeqie
  - terminal
  - thunar
  - vlc

- name: Include "gui-apps.yaml" tasks
  when:
  - user not in ["root", ansible_user] and gui_apps
  - ansible_distribution != 'Debian' or ansible_distribution_major_version | int >= 13
  include_tasks: gui-apps.yaml
  tags:
  - user-home
  - autostart
  - bootrun
  - mimeapps
  - geeqie
  - terminal
  - thunar
  - vlc
