- name: Copy file to "{{ home_directory }}/.login"
  copy:
    src: '{{ config_directory }}/login'
    dest: '{{ home_directory }}/.login'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0600'
  tags:
  - user-home

- name: Ensure "{{ home_directory }}/.ssh" directory exists
  file:
    path: '{{ home_directory }}/.ssh/'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0700'
  tags:
  - user-home
  - ssh

- name: Copy file to "{{ home_directory }}/.ssh/config"
  copy:
    src: '{{ config_directory }}/config'
    dest: '{{ home_directory }}/.ssh/config'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - ssh

- name: Check "{{ home_directory }}/.ssh/config-opt" file status
  stat:
    path: '{{ home_directory }}/.ssh/config-opt'
  register: ssh_config
  tags:
  - user-home
  - ssh

- name: Copy file to "{{ home_directory }}/.ssh/config-opt"
  when: not ssh_config.stat.exists
  copy:
    src: '{{ config_directory }}/config-opt'
    dest: '{{ home_directory }}/.ssh/config-opt'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - user-home
  - ssh

- name: Template file to "{{ home_directory }}/.config/netnice.json"
  when: download_rate
  template:
    src: netnice.json
    dest: '{{ home_directory }}/.config/'
    owner: '{{ user }}'
    group: '{{ group }}'
  tags:
  - local-system
  - netnice
